# Generated by Django 4.0.1 on 2022-01-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Description',
            field=models.CharField(max_length=150),
        ),
    ]
