# Generated by Django 4.0.1 on 2022-01-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Image',
            field=models.ImageField(blank=True, default='food.jpeg', upload_to=''),
        ),
    ]
