# Generated by Django 4.0.1 on 2022-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, default='food.jpeg', upload_to='')),
                ('recipe_count', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
